jobs:
  build_and_test:
    runs-on: self-hosted
    services:
      postgres:
        env:
          POSTGRES_PASSWORD: postgres
        image: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports:
        - 5432:5432
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      env:
        PGPASSWORD: postgres
      name: Create Database
      run: createdb --host=localhost --port=5432 --username=postgres nzyme-java-tests
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        architecture: x64
        java-package: jdk
        java-version: 11
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v1
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Clean Maven environment
      run: mvn clean
    - continue-on-error: true
      env:
        TEST_DATABASE_URL: postgresql://localhost:5432/nzyme-java-tests?user=postgres&password=postgres
      name: Build and Test
      run: mvn -B test
    - continue-on-error: true
      name: Upload Code Coverage
      uses: codecov/codecov-action@v1
name: Build and Test
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
